/*
Title: An Analysis of a UK-Based Online Store's Customer Transaction Data
Dataset: Online Retail.xlsx
Source: [Coursera] (https://www.coursera.org/projects/perform-exploratory-data-analysis-on-retail-data-with-python)
Objectives:
1. Assess sales trends over time (daily, monthly, yearly, day of week, seasons)
2. Assess sales trends by country (top-selling vs low-selling)
3. Assess sales trends by product (top-selling vs low-selling)
4. Determine the number of orders generated by month
5. Compare monthly revenue and monthly Orders
6. Determine monthly average order value
7. Determine most valuable customer(s)
8. Determine product popularity (by country)
9. Provide a high-level view of sales performance
*/

CREATE DATABASE UK_Retail_Sales_DB;

USE UK_Retail_Sales_DB;

-- Calculate Quartiles/IQR in SQL Server and create the final table
WITH Quartiles AS (
    SELECT 
        InvoiceNo,
        StockCode,
        Description,
        Quantity,
        InvoiceDate,
        UnitPrice,
        (Quantity * UnitPrice) AS LineTotal,
        CustomerID,
        Country,
        PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY Quantity) OVER () AS Q1_Quantity,
        PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY Quantity) OVER () AS Q3_Quantity,
        PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY UnitPrice) OVER () AS Q1_UnitPrice,
        PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY UnitPrice) OVER () AS Q3_UnitPrice
    FROM StagingOnlineRetail
),
Thresholds AS (
    SELECT 
        *,
        (Q1_Quantity - 1.5 * (Q3_Quantity - Q1_Quantity)) AS LowerBound_Quantity,
        (Q3_Quantity + 1.5 * (Q3_Quantity - Q1_Quantity)) AS UpperBound_Quantity,
        (Q1_UnitPrice - 1.5 * (Q3_UnitPrice - Q1_UnitPrice)) AS LowerBound_UnitPrice,
        (Q3_UnitPrice + 1.5 * (Q3_UnitPrice - Q1_UnitPrice)) AS UpperBound_UnitPrice
    FROM Quartiles
)
SELECT 
    InvoiceNo,
    StockCode,
    Description,
    Quantity,
    InvoiceDate,
    UnitPrice,
    CAST(LineTotal AS DECIMAL(18,2)) AS LineTotal,
    CustomerID,
    Country
INTO CleanedOnlineRetail
FROM Thresholds
WHERE 
    Quantity BETWEEN LowerBound_Quantity AND UpperBound_Quantity
    AND UnitPrice BETWEEN LowerBound_UnitPrice AND UpperBound_UnitPrice;

-- Optional: Clean up the staging table when finished
-- DROP TABLE StagingOnlineRetail;

-- Rename column 'LineTotal' to 'Sales'
EXEC sp_rename 'CleanedOnlineRetail.LineTotal', 'Sales', 'COLUMN';

-- View updated table
SELECT * FROM CleanedOnlineRetail;

/*
Sales Trends Over Time
Sales is broken down over 5 dimensions: yearly, monthly, daily, day of week, seasonal 
*/

-- 1a. Yearly Sales Trend
SELECT 
    YEAR(InvoiceDate) AS SalesYear,
    COUNT(DISTINCT InvoiceNo) AS TotalOrders,
    SUM(Quantity) AS TotalUnitsSold,
    SUM(Sales) AS TotalRevenue
INTO TrendYearly
FROM CleanedOnlineRetail
GROUP BY YEAR(InvoiceDate)
ORDER BY SalesYear;

-- View new table
SELECT * FROM TrendYearly;

-- 1b. Monthly Sales Trend
SELECT 
    YEAR(InvoiceDate) AS SalesYear,
    MONTH(InvoiceDate) AS SalesMonth,
    DATENAME(month, InvoiceDate) AS MonthName,
    COUNT(DISTINCT InvoiceNo) AS TotalOrders,
    SUM(Sales) AS TotalRevenue
INTO TrendMonthly
FROM CleanedOnlineRetail
GROUP BY YEAR(InvoiceDate), MONTH(InvoiceDate), DATENAME(month, InvoiceDate)
ORDER BY SalesYear, SalesMonth;

-- View new table
SELECT * FROM TrendMonthly;

-- 1c. Daily Sales Trend
SELECT 
    CAST(InvoiceDate AS DATE) AS SalesDate,
    COUNT(DISTINCT InvoiceNo) AS TotalOrders,
    SUM(Sales) AS TotalRevenue
INTO TrendDaily
FROM CleanedOnlineRetail
GROUP BY CAST(InvoiceDate AS DATE)
ORDER BY SalesDate;

-- View new table
SELECT * FROM TrendDaily;

-- 1d. Day of Week Sales Trend
SELECT 
    DATEPART(weekday, InvoiceDate) AS DayOfWeekNumber,
    DATENAME(weekday, InvoiceDate) AS DayOfWeekName,
    COUNT(DISTINCT InvoiceNo) AS TotalOrders,
    SUM(Sales) AS TotalRevenue
INTO TrendDayOfWeek
FROM CleanedOnlineRetail
GROUP BY DATEPART(weekday, InvoiceDate), DATENAME(weekday, InvoiceDate)
ORDER BY DayOfWeekNumber;

-- View new table
SELECT * FROM TrendDayOfWeek;

-- 1e. Seasonal Sales Trend
SELECT 
    CASE 
        WHEN MONTH(InvoiceDate) IN (12, 1, 2) THEN 'Winter'
        WHEN MONTH(InvoiceDate) IN (3, 4, 5) THEN 'Spring'
        WHEN MONTH(InvoiceDate) IN (6, 7, 8) THEN 'Summer'
        WHEN MONTH(InvoiceDate) IN (9, 10, 11) THEN 'Autumn'
    END AS Season,
    COUNT(DISTINCT InvoiceNo) AS TotalOrders,
    SUM(Sales) AS TotalRevenue
INTO TrendSeasonal
FROM CleanedOnlineRetail
GROUP BY 
    CASE 
        WHEN MONTH(InvoiceDate) IN (12, 1, 2) THEN 'Winter'
        WHEN MONTH(InvoiceDate) IN (3, 4, 5) THEN 'Spring'
        WHEN MONTH(InvoiceDate) IN (6, 7, 8) THEN 'Summer'
        WHEN MONTH(InvoiceDate) IN (9, 10, 11) THEN 'Autumn'
    END
ORDER BY TotalRevenue DESC;

-- View new table
SELECT * FROM TrendSeasonal;

/*
Sales Trends by Country (Top-Selling vs Low-Selling)
Countries are ranked by total revenue (sales) and order volume
*/
SELECT 
    Country,
    COUNT(DISTINCT InvoiceNo) AS TotalOrders,
    SUM(Quantity) AS TotalUnitsSold,
    SUM(Sales) AS TotalRevenue,
    CAST(AVG(Sales) AS DECIMAL(18,2)) AS AvgSalesValue
INTO CountrySalesPerformance
FROM CleanedOnlineRetail
GROUP BY Country
ORDER BY TotalRevenue DESC;

-- View new table
SELECT * FROM CountrySalesPerformance;

/*
Sales Trends by Product (Top-Selling vs Low-Selling)
Products are ranked by total revenue (sales) and volume sold
*/
SELECT 
    StockCode,
    Description,
    SUM(Quantity) AS TotalUnitsSold,
    SUM(Sales) AS TotalRevenue,
    COUNT(DISTINCT InvoiceNo) AS OrderCount
INTO ProductSalesPerformance
FROM CleanedOnlineRetail
GROUP BY StockCode, Description
ORDER BY TotalRevenue DESC;

-- View new table
SELECT * FROM ProductSalesPerformance;

/*
Monthly Orders, Revenue Comparison & Average Order Value (AOV)
Compares monthly order volume, monthly revenue & AOV (calculated as total revenue/total orders)
*/
SELECT 
    YEAR(InvoiceDate) AS SalesYear,
    MONTH(InvoiceDate) AS SalesMonth,
    DATENAME(month, InvoiceDate) AS MonthName,
    -- Objective 4: Monthly Orders
    COUNT(DISTINCT InvoiceNo) AS MonthlyOrders,
    -- Objective 5: Monthly Revenue
    SUM(Sales) AS MonthlyRevenue,
    -- Objective 6: Average Order Value
    CAST(SUM(Sales) / COUNT(DISTINCT InvoiceNo) AS DECIMAL(18,2)) AS AverageOrderValue
INTO MonthlyMetrics
FROM CleanedOnlineRetail
GROUP BY YEAR(InvoiceDate), MONTH(InvoiceDate), DATENAME(month, InvoiceDate)
ORDER BY SalesYear, SalesMonth;

-- View new table
SELECT * FROM MonthlyMetrics;

/*
Determine Most Valuable Customer(s)
Customers are ranked based on total spend, order frequency and average spend per order. 
** Guest customers (those without ID) are excluded
*/
SELECT 
    CustomerID,
    COUNT(DISTINCT InvoiceNo) AS TotalOrders,
    SUM(Quantity) AS TotalItemsPurchased,
    SUM(Sales) AS TotalSpend,
    CAST(SUM(Sales) / COUNT(DISTINCT InvoiceNo) AS DECIMAL(18,2)) AS CustomerAOV
INTO TopCustomers
FROM CleanedOnlineRetail
WHERE CustomerID IS NOT NULL
GROUP BY CustomerID
ORDER BY TotalSpend DESC;

-- View new table
SELECT * FROM TopCustomers;

/*
Product Popularity by Country
Ranks top 5 products sold in each country
*/
WITH RankedProducts AS (
    SELECT 
        Country,
        StockCode,
        Description,
        SUM(Quantity) AS UnitsSold,
        SUM(Sales) AS TotalRevenue,
        RANK() OVER (
            PARTITION BY Country 
            ORDER BY SUM(Quantity) DESC
        ) AS PopularityRank
    FROM CleanedOnlineRetail
    GROUP BY Country, StockCode, Description
)
SELECT 
    Country,
    PopularityRank,
    StockCode,
    Description,
    UnitsSold,
    TotalRevenue
INTO ProductPopularityByCountry
FROM RankedProducts
WHERE PopularityRank <= 5; -- Filter to top 5 products per country

-- View new table
SELECT * FROM ProductPopularityByCountry;

/*
High-Level View of Sales Performance
Executive-level summary of business performance
*/
SELECT 
    SUM(Sales) AS OverallRevenue,
    COUNT(DISTINCT InvoiceNo) AS OverallOrders,
    COUNT(DISTINCT CustomerID) AS UniqueCustomers,
    COUNT(DISTINCT StockCode) AS UniqueProductsSold,
    COUNT(DISTINCT Country) AS MarketsServed,
    SUM(Quantity) AS TotalUnitsSold,
    CAST(SUM(Sales) / COUNT(DISTINCT InvoiceNo) AS DECIMAL(18,2)) AS OverallAOV
INTO HighLevelSalesSummary
FROM CleanedOnlineRetail;

-- View new table
SELECT * FROM HighLevelSalesSummary;